import { Link } from 'react-router-dom';
import { ArrowDownRight, ArrowUpRight, Sparkles } from 'lucide-react';
import PageHeader, { EmptyState, Metric } from '../components/PageHeader';

export default function DecisionExplanation({ assessment }) {
  if (!assessment) return <><PageHeader eyebrow="Decision explanation" title="Why was this prediction made?" /><EmptyState /></>;
  const { prediction, decision, explanation, applicant } = assessment;
  const increasing = explanation?.increasing_risk || []; const reducing = explanation?.reducing_risk || [];
  return <><PageHeader eyebrow="Decision explanation" title="Why was this prediction made?" description={`A local explanation for ${applicant.name}'s individual assessment.`} action={<Link className="mustard-button" to="/risk-analysis">Back to risk analysis</Link>} />
    <div className="decision-intro"><div><span>Your application was classified as</span><strong>{prediction.class.toUpperCase()}</strong></div><div className="metrics-grid four"><Metric label="Default risk" value={`${prediction.default_probability_percent.toFixed(2)}%`} tone="risk"/><Metric label="Non-default" value={`${prediction.non_default_probability_percent.toFixed(2)}%`} tone="positive"/><Metric label="Risk level" value={decision.risk_level}/><Metric label="Recommendation" value={decision.recommendation}/></div></div>
    {!explanation?.available ? <div className="empty-state"><Sparkles size={22}/><p>Prediction is available, but the detailed explanation could not be generated.</p></div> : <><div className="explanation-grid"><FactorSection title="What increased your risk?" subtitle="Factors contributing toward higher estimated default risk." factors={increasing} tone="risk"/><FactorSection title="What reduced your risk?" subtitle="Factors contributing toward lower estimated default risk." factors={reducing} tone="positive"/></div><section className="panel influenced"><p className="eyebrow">Overall explanation</p><h2>What influenced your result?</h2><p>{buildSummary(increasing, reducing)}</p><small>These are the factors that had the strongest influence on this individual prediction.</small></section></>}
  </>;
}
function FactorSection({ title, subtitle, factors, tone }) { return <section className={`factor-section ${tone}`}><div className="section-title"><div className="factor-icon">{tone === 'risk' ? <ArrowUpRight size={18}/> : <ArrowDownRight size={18}/>}</div><div><h2>{title}</h2><p>{subtitle}</p></div></div>{factors.slice(0,5).map((factor, index) => <article className="factor-card" key={`${factor.feature}-${index}`}><div className="factor-number">0{index+1}</div><div><h3>{factor.label}</h3><strong>{formatValue(factor.label, factor.value)}</strong><p>{factor.message}</p></div></article>)}{!factors.length && <p className="muted">No factors were returned in this category.</p>}</section>; }
function formatValue(label, value) { if (value == null) return 'Not provided'; if (['Loan Amount','Annual Income','Monthly Installment','Revolving Balance','Total Collection Amount','Total Current Balance'].includes(label)) return `$${Number(value).toLocaleString()}`; if (['Interest Rate','Debt-to-Income Ratio','Revolving Credit Utilization'].includes(label)) return `${Number(value).toFixed(1)}%`; if (label === 'Loan Term') return `${Number(value)} months`; return String(value); }
function buildSummary(up, down) { const names = items => items.slice(0,3).map(item => item.label); const upNames = names(up); const downNames = names(down); const join = values => values.length > 1 ? `${values.slice(0,-1).join(', ')} and ${values.at(-1)}` : values[0]; return `${upNames.length ? `Your assessment was influenced by ${join(upNames)}, which contributed to higher estimated default risk.` : ''} ${downNames.length ? `${join(downNames)} helped reduce the estimated risk.` : ''}`.trim(); }
