import { useState } from 'react';
import { FileUp, LoaderCircle, UploadCloud } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import { createAssessment } from '../services/api';

const PURPOSES = ['credit_card','debt_consolidation','educational','home_improvement','house','major_purchase','medical','moving','other','renewable_energy','small_business','vacation','wedding'];
const HOMES = ['RENT','MORTGAGE','OWN','NONE','OTHER'];
const CREDIT_FIELDS = ['delinq_2yrs','earliest_cr_line','fico_range_low','fico_range_high','inq_last_6mths','mths_since_last_delinq','mths_since_last_record','open_acc','pub_rec','revol_bal','revol_util','total_acc','acc_now_delinq','tot_coll_amt','tot_cur_bal','mort_acc','pub_rec_bankruptcies','tax_liens'];

function Field({ label, children, hint }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }

export default function NewAssessment({ onAssessment }) {
  const [form, setForm] = useState({ full_name:'', loan_amnt:15000, term:36, annual_inc:60000, purpose:'debt_consolidation', dti:20, installment:500, emp_length:'5 years', home_ownership:'RENT', application_type:'Individual' });
  const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event) { event.preventDefault(); setError(''); if (!file) return setError('Upload the applicant credit report TXT file to continue.'); setBusy(true); try { const result = await createAssessment({ full_name: form.full_name }, form, file); onAssessment(result); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="New assessment" title="Build an applicant assessment" description="A complete, applicant-specific prediction using the existing XGBoost and local SHAP pipeline." />
    <form className="assessment-form" onSubmit={submit}>
      <section className="form-section"><div className="section-kicker">01 <span>Applicant information</span></div><div className="form-grid two"><Field label="Full name"><input required value={form.full_name} onChange={e => update('full_name', e.target.value)} placeholder="Joann Johnson" /></Field><Field label="Applicant age" hint="Display-only"><input type="number" min="18" max="100" value={form.age || ''} onChange={e => update('age', e.target.value)} placeholder="32" /></Field></div></section>
      <section className="form-section"><div className="section-kicker">02 <span>Application details</span></div><div className="form-grid three"><Field label="Loan amount"><input required type="number" min="1" value={form.loan_amnt} onChange={e => update('loan_amnt', Number(e.target.value))} /></Field><Field label="Loan term"><select value={form.term} onChange={e => update('term', Number(e.target.value))}><option value="36">36 months</option><option value="60">60 months</option></select></Field><Field label="Annual income"><input required type="number" min="1" value={form.annual_inc} onChange={e => update('annual_inc', Number(e.target.value))} /></Field><Field label="Monthly installment"><input required type="number" min="0" value={form.installment} onChange={e => update('installment', Number(e.target.value))} /></Field><Field label="Debt-to-income ratio"><input required type="number" min="0" max="100" step="0.1" value={form.dti} onChange={e => update('dti', Number(e.target.value))} /></Field><Field label="Loan purpose"><select value={form.purpose} onChange={e => update('purpose', e.target.value)}>{PURPOSES.map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Employment length"><select value={form.emp_length} onChange={e => update('emp_length', e.target.value)}>{['< 1 year',...Array.from({length:9},(_,i)=>`${i+1} years`),'10+ years'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Home ownership"><select value={form.home_ownership} onChange={e => update('home_ownership', e.target.value)}>{HOMES.map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Application type"><select value={form.application_type} onChange={e => update('application_type', e.target.value)}><option>Individual</option><option>Joint App</option></select></Field></div></section>
      <section className="form-section"><div className="section-kicker">03 <span>Credit report</span></div><div className="upload-box"><UploadCloud size={26}/><div><strong>Upload Credit Report</strong><p>Use the TXT report with one field per line, such as <code>fico_range_low: 675</code>.</p></div><label className="file-button"><FileUp size={16}/> {file ? file.name : 'Choose TXT file'}<input required type="file" accept=".txt,text/plain" onChange={e => setFile(e.target.files?.[0] || null)} /></label></div><p className="field-note">Required fields: {CREDIT_FIELDS.join(', ')}</p></section>
      <section className="form-section lender-section"><div className="section-kicker">04 <span>Lender information</span></div><div><h3>Predefined for this assessment</h3><p>The single-lender prototype supplies interest rate, verification status, issue date, and listing status through the backend configuration.</p></div><div className="lender-values"><span>12.5% interest</span><span>Source Verified</span><span>Dec-2015 issue date</span></div></section>
      {error && <div className="error-banner">{error}</div>}<button className="primary-button submit-button" disabled={busy}>{busy ? <><LoaderCircle className="spin" size={18}/> Analyzing application...</> : 'Run assessment'}</button>
    </form></>;
}
